In [7]:
#Using the selected features run  svm  model to predict "revenue" and evalaute the results 


In [8]:
import numpy as np 
import pandas as pd 

In [9]:
import matplotlib.pyplot as plt

In [10]:
df= pd.read_csv('Final_Model_data.csv',header=0,encoding = 'unicode_escape',index_col='rownum')

In [11]:
df.head()

budget     id               original_title  popularity    revenue  \
rownum                                                                        
1       30000000    862                    Toy Story   21.946943  373554033   
2       65000000   8844                      Jumanji   17.015539  262797249   
3       16000000  31357            Waiting to Exhale    3.859495   81452156   
4              0  11862  Father of the Bride Part II    8.387519   76578911   
5       60000000    949                         Heat   17.924927  187436818   

        runtime  vote_average  vote_count  weighted_rating  cast_size  \
rownum                                                                  
1            81           7.7        5415         7.684645         13   
2           104           6.9        2413         6.876926         26   
3           127           6.1          34         5.675590         10   
4           106           5.7         173         5.624595         12   
5           170           7.7        1886         7.656437         65   

            ...        Genre_History  Genre_Horror  Genre_Music  \
rownum      ...                                                   
1           ...                    0             0            0   
2           ...                    0             0            0   
3           ...                    0             0            0   
4           ...                    0             0            0   
5           ...                    0             0            0   

        Genre_Mystery  Genre_Romance  Genre_Science Fiction  Genre_TV Movie  \
rownum                                                                        
1                   0              0                      0               0   
2                   0              0                      0               0   
3                   0              0                      0               0   
4                   0              0                      0               0   
5                   0              0                      0               0   

        Genre_Thriller  Genre_War  Genre_Western  
rownum                                            
1                    0          0              0  
2                    0          0              0  
3                    0          0              0  
4                    0          0              0  
5                    0          0              0  

[5 rows x 38 columns]

In [12]:
df.dtypes

budget                     int64
id                         int64
original_title            object
popularity               float64
revenue                    int64
runtime                    int64
vote_average             float64
vote_count                 int64
weighted_rating          float64
cast_size                  int64
crew_size                  int64
revenue_divide_budget    float64
movie_count                int64
director_Rank              int64
collection_Rank            int64
prod_Comp_Rank             int64
genres_Rank                int64
Genre_0                    int64
Genre_Action               int64
Genre_Adventure            int64
Genre_Animation            int64
Genre_Comedy               int64
Genre_Crime                int64
Genre_Documentary          int64
Genre_Drama                int64
Genre_Family               int64
Genre_Fantasy              int64
Genre_Foreign              int64
Genre_History              int64
Genre_Horror               int64
Genre_Musi

In [13]:
df.shape

(46623, 38)

In [14]:
#df.loc[df['revenue'] == 0.0]

In [15]:
df[df.revenue == 0.0]

budget      id                                     original_title  \
rownum                                                                        
6       58000000   11860                                            Sabrina   
7              0   45325                                       Tom and Huck   
11             0   12110                        Dracula: Dead and Loving It   
21             0    1710                                            Copycat   
23             0   12665                                             Powder   
25             0   16420                                            Othello   
27             0   17015                                         Persuasion   
29             0   37557                        ¾ÔàŒ¥_¾Ôà•_ξÔàŒö¡Œ_Ќ© ¾Á´   
32             0   78802                   Guillaumet, les ailes du courage   
34             0   47018                                         Carrington   
36             0  139405                             Across the Sea of Time   
37             0   33689                                       It Takes Two   
38      12000000    9603                                           Clueless   
40             0   31174                                        Richard III   
41      10000000   11443                                    Dead Presidents   
42      19000000   35196                                        Restoration   
48             0    8391                              When Night Is Falling   
50             0  117164                                     Guardian Angel   
52             0   49133                                           Lamerica   
53             0   26441                                      The Big Green   
54             0   97406                                            Georgia   
55             0  124057                            Kids of the Round Table   
57             0   11010                                         Il postino   
58             0   99040                                   Le confessionnal   
59      45000000   11359                         The Indian in the Cupboard   
60      20000000   17182                                     Eye for an Eye   
62             0   10607  Don't Be a Menace to South Central While Drink...   
63             0   19760                                      Two If by Sea   
64      15000000    9536                                           Bio-Dome   
66             0   40628                                           Two Bits   
...          ...     ...                                                ...   
46594          0   45527                                    The Final Storm   
46595          0  455661                                     In a Heartbeat   
46596          0  327237                             Bloed, Zweet en Tranen   
46597          0   84710                                       Jungle Woman   
46598          0   39562                                  To Be Fat Like Me   
46599          0   14008                                        Cadet Kelly   
46600          0   44330                               Le tripot clandestin   
46601          0   49279                  L'Homme ÌÊ la tÌ»te de caoutchouc   
46602          0   44333                                Les cartes vivantes   
46603          0   49277                           Les affiches en goguette   
46604          0   49271                            Le locataire diabolique   
46605          0   44324                               Le Roi du maquillage   
46606          0  122036                  Les Transmutations imperceptibles   
46607          0   14885                   Pooh's Heffalump Halloween Movie   
46608          0   49280                                  L'Homme orchestre   
46609          0  106807                     Nouvelles luttes extravagantes   
46610          0  276895                                        Deep Hearts   
46611          0  404604                                    

In [16]:
df[df.budget == 0.0]

budget      id                                     original_title  \
rownum                                                                      
4            0   11862                        Father of the Bride Part II   
7            0   45325                                       Tom and Huck   
11           0   12110                        Dracula: Dead and Loving It   
12           0   21032                                              Balto   
21           0    1710                                            Copycat   
23           0   12665                                             Powder   
25           0   16420                                            Othello   
27           0   17015                                         Persuasion   
29           0   37557                        ¾ÔàŒ¥_¾Ôà•_ξÔàŒö¡Œ_Ќ© ¾Á´   
30           0    9909                                    Dangerous Minds   
32           0   78802                   Guillaumet, les ailes du courage   
34           0   47018                                         Carrington   
36           0  139405                             Across the Sea of Time   
37           0   33689                                       It Takes Two   
39           0   34615                           Cry, the Beloved Country   
40           0   31174                                        Richard III   
48           0    8391                              When Night Is Falling   
50           0  117164                                     Guardian Angel   
52           0   49133                                           Lamerica   
53           0   26441                                      The Big Green   
54           0   97406                                            Georgia   
55           0  124057                            Kids of the Round Table   
56           0    9089                              Home for the Holidays   
57           0   11010                                         Il postino   
58           0   99040                                   Le confessionnal   
61           0    2054                                 Mr. Holland's Opus   
62           0   10607  Don't Be a Menace to South Central While Drink...   
63           0   19760                                      Two If by Sea   
65           0   11525                 Lawnmower Man 2: Beyond Cyberspace   
66           0   40628                                           Two Bits   
...        ...     ...                                                ...   
46594        0   45527                                    The Final Storm   
46595        0  455661                                     In a Heartbeat   
46596        0  327237                             Bloed, Zweet en Tranen   
46597        0   84710                                       Jungle Woman   
46598        0   39562                                  To Be Fat Like Me   
46599        0   14008                                        Cadet Kelly   
46600        0   44330                               Le tripot clandestin   
46601        0   49279                  L'Homme ÌÊ la tÌ»te de caoutchouc   
46602        0   44333                                Les cartes vivantes   
46603        0   49277                           Les affiches en goguette   
46604        0   49271                            Le locataire diabolique   
46605        0   44324                               Le Roi du maquillage   
46606        0  122036                  Les Transmutations imperceptibles   
46607        0   14885                   Pooh's Heffalump Halloween Movie   
46608        0   49280                                  L'Homme orchestre   
46609        0  106807                     Nouvelles luttes extravagantes   
46610        0  276895                                        Deep Hearts   
46611        0  404604                                                Maa   
46612        0  420346                                  The Morning After   
4661

In [17]:
indexNames = df[ (df['revenue'] == 0.0) | (df['budget'] == 0.0) ].index

In [18]:
indexNames = df[ (df['revenue'] < 1000.0) | (df['budget'] < 1000.0) ].index

In [19]:
#indexNames

In [20]:
df.drop(indexNames , inplace=True)

In [21]:
df.shape

(5383, 38)

In [22]:
df.head()

budget     id     original_title  popularity    revenue  runtime  \
rownum                                                                       
1       30000000    862          Toy Story   21.946943  373554033       81   
2       65000000   8844            Jumanji   17.015539  262797249      104   
3       16000000  31357  Waiting to Exhale    3.859495   81452156      127   
5       60000000    949               Heat   17.924927  187436818      170   
8       35000000   9091       Sudden Death    5.231580   64350171      106   

        vote_average  vote_count  weighted_rating  cast_size      ...        \
rownum                                                            ...         
1                7.7        5415         7.684645         13      ...         
2                6.9        2413         6.876926         26      ...         
3                6.1          34         5.675590         10      ...         
5                7.7        1886         7.656437         65      ...         
8                5.5         174         5.457491          6      ...         

        Genre_History  Genre_Horror  Genre_Music  Genre_Mystery  \
rownum                                                            
1                   0             0            0              0   
2                   0             0            0              0   
3                   0             0            0              0   
5                   0             0            0              0   
8                   0             0            0              0   

        Genre_Romance  Genre_Science Fiction  Genre_TV Movie  Genre_Thriller  \
rownum                                                                         
1                   0                      0               0               0   
2                   0                      0               0               0   
3                   0                      0               0               0   
5                   0                      0               0               0   
8                   0                      0               0               0   

        Genre_War  Genre_Western  
rownum                            
1               0              0  
2               0              0  
3               0              0  
5               0              0  
8               0              0  

[5 rows x 38 columns]

In [23]:
df = df.drop(['id', 'original_title','revenue_divide_budget'], axis=1)

In [24]:
df.shape

(5383, 35)

In [25]:
# Put the target revenue in another DataFrame
target = pd.DataFrame(df.revenue, columns=["revenue"])

In [26]:
df = df.drop(['revenue'], axis=1)

In [27]:
X = df
y = target['revenue']

In [28]:
X.shape

(5383, 34)

In [29]:
# Import `RandomForestClassifier`
from sklearn.ensemble import RandomForestClassifier


# Build the model
rfc = RandomForestClassifier()

# Fit the model
rfc.fit(X, y)

names = df.columns.values

# Print the results
print("Features sorted by their score:")
print(sorted(zip(map(lambda x: round(x, 4), rfc.feature_importances_), names), reverse=True))

Features sorted by their score:
[(0.0944, 'vote_count'), (0.0935, 'popularity'), (0.0899, 'weighted_rating'), (0.0898, 'runtime'), (0.0883, 'cast_size'), (0.0868, 'crew_size'), (0.0864, 'director_Rank'), (0.0859, 'budget'), (0.0843, 'prod_Comp_Rank'), (0.0803, 'vote_average'), (0.0371, 'collection_Rank'), (0.0217, 'genres_Rank'), (0.0091, 'Genre_Comedy'), (0.0088, 'Genre_Drama'), (0.0075, 'Genre_Action'), (0.0044, 'Genre_Horror'), (0.0042, 'Genre_Thriller'), (0.0035, 'Genre_Crime'), (0.0033, 'Genre_Fantasy'), (0.0031, 'Genre_Romance'), (0.003, 'Genre_Adventure'), (0.0021, 'Genre_Science Fiction'), (0.0021, 'Genre_Mystery'), (0.002, 'Genre_Animation'), (0.0015, 'Genre_Family'), (0.0013, 'Genre_War'), (0.0012, 'Genre_History'), (0.0012, 'Genre_Documentary'), (0.0011, 'Genre_Western'), (0.0011, 'Genre_Music'), (0.0004, 'Genre_0'), (0.0003, 'Genre_Foreign'), (0.0001, 'Genre_TV Movie'), (0.0, 'movie_count')]


In [ ]:
plt.subplots(figsize=(15, 12))

# Isolate feature importances 
importance = rfc.feature_importances_

# Sort the feature importances 
sorted_importances = np.argsort(importance)

# Insert padding
padding = np.arange(len(names)-1) + 0.5
 
padding = padding[10:34]
sorted_importances = sorted_importances[10:33] 

# Plot the data
plt.barh(padding, importance[sorted_importances], align='center')

# Customize the plot
plt.yticks(padding, names[sorted_importances])
plt.xlabel("Relative Importance")
plt.title("Variable Importance")

# Show the plot
plt.show()

In [30]:
X=df[['vote_count','budget','weighted_rating','runtime','cast_size','director_Rank','crew_size','prod_Comp_Rank','vote_average']]

In [31]:
type(X)

pandas.core.frame.DataFrame

In [32]:
X.shape

(5383, 9)

In [33]:
type(y)

pandas.core.series.Series

In [34]:
y.shape

(5383,)

In [119]:
# Import train_test_split function
from sklearn.model_selection import train_test_split


# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test

In [120]:
y_test.shape

(1615,)

In [121]:
y_test

rownum
15677    170432927
6736      13007551
18315     17511906
43245      9100000
1095      20300385
15612    293329073
309        9771658
13690     87784194
16523       187716
16776    108609310
1089       1227324
19583      1620436
2932      32056467
21180     23198652
7803        485772
13838     10000000
17309         7306
19909        31649
1785     379014294
38653     18000000
28515     12314651
22924     34077920
4905      92542418
8347      22000000
1557     131457682
32931     64191523
12847     14723313
11538     49469904
4582      25928721
24405    255273813
           ...    
161       16140822
893       72070731
16548     11087569
32544     27139524
18562     12355798
12871     63800345
1251     146900000
5230      19319254
1602       2642983
7311     130293714
6830       7808524
34425       340312
6408       8000000
3692     133949270
32479     34854990
12277    585349010
45057        33700
1065     213954274
23661     30000000
23518     18662027
7043      96269812
12762

In [122]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
#from sklearn.preprocessing import PolynomialFeatures
#from sklearn.linear_model import Ridge
from sklearn import svm
from sklearn.svm import SVR
from sklearn.svm import LinearSVR

In [123]:
#from sklearn.preprocessing import PolynomialFeatures
#polynomial_features= PolynomialFeatures(degree=9)

#X_train = polynomial_features.fit_transform(X_train)

#X_test = polynomial_features.fit_transform(X_test)

In [124]:
from sklearn import preprocessing

In [125]:
from sklearn.preprocessing import MinMaxScaler
#scaling = MinMaxScaler(feature_range=(-1,1)).fit(X_train)
#from sklearn.preprocessing import StandardScaler

#X_train = scaling.transform(X_train)
#X_test = scaling.transform(X_test)

#scalerX = StandardScaler().fit(X_train)

y_train = y_train.reshape(-1, 1)
#scalery = StandardScaler().fit(y_train)

#X_train = scalerX.transform(X_train)
#y_train = scalery.transform(y_train)

y_test = y_test.reshape(-1, 1)
#X_test = scalerX.transform(X_test)
#y_test = scalery.transform(y_test)

scaler = preprocessing.MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
y_train = scaler.fit_transform(y_train)
y_test = scaler.fit_transform(y_test)


/Users/APM/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  # Remove the CWD from sys.path while we load stuff.
/Users/APM/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  app.launch_new_instance()
/Users/APM/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [126]:
X_train

array([[0.16042629, 0.25788985, 0.5221636 , ..., 0.03481013, 0.08199234,
        0.68965517],
       [0.00120782, 0.03157258, 0.40924372, ..., 0.00632911, 0.14559387,
        0.65517241],
       [0.08703375, 0.03946736, 0.61345341, ..., 0.19303797, 0.16475096,
        0.74712644],
       ...,
       [0.01811723, 0.07894131, 0.45659311, ..., 0.07911392, 0.15249042,
        0.65517241],
       [0.00632327, 0.06841492, 0.33167703, ..., 0.19620253, 0.10268199,
        0.56321839],
       [0.0068206 , 0.00788821, 0.61399995, ..., 0.0443038 , 0.        ,
        0.79310345]])

In [127]:
y_train

array([[0.15531475],
       [0.00177138],
       [0.02304084],
       ...,
       [0.00913896],
       [0.01391405],
       [0.00354329]])

In [128]:
#We call the SVC method from the sklearn library which creates the necessary object for fitting
#model = svm.SVC(gamma='scale')
#model = svm.SVR(kernel="linear")
model = SVR(kernel='poly',degree=2, C=100, epsilon=.1)
#model = LinearSVR(epsilon=1.5)


In [129]:
#Simply fit the values of X and Y
model.fit(X_train, y_train)

/Users/APM/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=100, cache_size=200, coef0=0.0, degree=2, epsilon=0.1, gamma='auto',
  kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [130]:
# predicting on training data-set
y_train_predicted = model.predict(X_train)
  

In [131]:
y_train_predicted

array([0.14905798, 0.05330648, 0.03792387, ..., 0.08459082, 0.07126521,
       0.06979947])

In [132]:
#MinMaxScaler.inverse_transform(y_train_predicted, y_train_predicted)
#y_train_predicted = scalery.inverse_transform(y_train_predicted)

In [133]:
y_train_predicted[200:250]

array([ 0.04412527, -0.00745661,  0.02737441,  0.06504395,  0.10797164,
        0.00750239,  0.14008943,  0.24987675,  0.07255291, -0.01798925,
        0.00703952,  0.05669188,  0.00908972,  0.17686313,  0.09288744,
        0.09236168, -0.01624923,  0.05842016,  0.12856642,  0.02593955,
        0.0218121 ,  0.02979528,  0.10270952, -0.01070055,  0.1332882 ,
        0.09213661,  0.0632414 ,  0.00401074,  0.1826088 ,  0.05570275,
        0.05543501, -0.04741296,  0.12500557,  0.02501532,  0.08922301,
        0.05060626,  0.02081561, -0.01210038,  0.09445072,  0.05382329,
        0.08096426,  0.05778981,  0.03992915,  0.10260113,  0.06302496,
        0.04208853,  0.01143673,  0.02523116,  0.03545315,  0.07059917])

In [134]:
 # evaluating the model on training dataset
rmse_train = np.sqrt(mean_squared_error(y_train, y_train_predicted))
r2_train = r2_score(y_train, y_train_predicted)
#print(r2_train)

In [135]:
print("The model performance for the training set")
print("-------------------------------------------")
print("RMSE of training set is {}".format(rmse_train))
print("R2 score of training set is {}".format(r2_train))
  
  

The model performance for the training set
-------------------------------------------
RMSE of training set is 0.05269715586811493
R2 score of training set is 0.25401481398971293


In [136]:
y_test

array([[0.11215861],
       [0.00855905],
       [0.0115233 ],
       ...,
       [0.01171788],
       [0.02081018],
       [0.04387591]])

In [137]:

y_test_pred = model.predict(X_test)

In [138]:
y_test_pred

array([0.14285884, 0.007941  , 0.01868466, ..., 0.09106069, 0.03455781,
       0.06441888])

In [141]:
y_test_pred = y_test_pred.reshape(-1, 1)


In [142]:
y_test_pred = scaler.inverse_transform(y_test_pred)

In [166]:
y_test = y_test.reshape(-1, 1)

In [167]:
y_test = scaler.inverse_transform(y_test)

In [179]:
#y_test_pred_series = pd.Series((y_test_pred))

In [175]:
y_test_pred

array([[2.17083653e+08],
       [1.20683917e+07],
       [2.83939947e+07],
       ...,
       [1.38373436e+08],
       [5.25141330e+07],
       [9.78897136e+07]])

In [176]:
from sklearn.metrics import mean_squared_error, r2_score

In [177]:
 # evaluating the model on test dataset
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_test = r2_score(y_test, y_test_pred_series)

In [178]:
print("The model performance for the test set")
print("-------------------------------------------")
print("RMSE of test set is {}".format(rmse_test))
print("R2 score of test set is {}".format(r2_test))

The model performance for the test set
-------------------------------------------
RMSE of test set is 4.2046649161158934e+26
R2 score of test set is -0.32689392720286015


In [173]:
#https://towardsdatascience.com/ridge-and-lasso-regression-a-complete-guide-with-python-scikit-learn-e20e34bcbf0b